[project]
name = "streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.10"
dependencies = [
    "google-cloud-aiplatform>=1.115.0",
    "requests>=2.32.5",
    "streamlit>=1.49.1",
]
